### ISSUE TITLE
First Test 1.0

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth_DMM_For_Windows_MQTT_Test_Project#1]
First MQTT Test
and wishes + Ideas

Enviroment:
Using a mosquitto server on a Raspberry
Using a Node Red instance on a other Client SBC

![image](https://user-images.githubusercontent.com/12202733/182036021-2bf6c8cc-8ecb-4e38-9b7f-a75368935d2d.png)

- transmition looks good
- unicode/ Symbols µ etc. are OK

IS:
BT_DMM/V05B : msg.payload : string[8]
"  27:°C:"

Idea to change Payloadformat: (quick idea)
Example1:  "{ Time: "2022-07-31T17:33:00", BT_DMM: "V05B", Value: "Unit"}"
Example1A:  "{ Time: "2022-07-31T17:33:00", BT_DMM: "V05B", Value: "Unit", Current: "DC"}"
BT_DMM: "CLIENT"
Current: "DC"
Current: "AC"
Diode: ".OL"

Example2+SI.   "{ Time: "2022-07-31T17:33:00", BT_DMM: "V05B", Value: "Unit", Value: "SI-Unit"}"
Example2         :"{ Time: "2022-07-31T17:33:00", BT_DMM: "V05B", 100.0: "mV", 0.100: "V"}"

Example other MQTT Clients i use:

Tasmota:
"{ Time: "2022-07-31T17:33:00", BME280: object, ESP32: object, PressureUnit: "hPa", TempUnit: "C" }"

RTL_433:
"{ time: "2022-07-31 16:31:43", model: "GT-WT02", id: 188, channel: 1, battery_ok: 0 … }"

DWD Deutscher Wetterdienst:
"{ station: "MUENCHEN STADT", tempc: 26.1, humidity: 35.7, windspeed: 3.8, winddirection: 285.9 … }"

Tasmota2
"{"Time":"2022-07-31T18:42:00","TSL2561":{"Illuminance":428.000,"IR":12080,"Broadband":30864}}"

Own Device:
"{"Time":"2022-07-31 18:40:01","BME280":{"Temperature": 26.7,"Pressure":950.9,"Humidity": 43.9},"TempUnit":"C"}"

You are very fast !! +++

ludwich

**Comment by webspiderteam** [comment]
I can change format Its not problem but keeping data lenght sort is better for data speed and beware data loss but its no problem. 
Time? but why. target system can get their clock

**Comment by ludwich66** [comment]
Hi Engin,

please change to JSON Format with  Key:Value format.

about timestamp: 
a timestamp is useful to find the right order, MQTT is caching messages if connection is lost or broken.
i meen Transfer is’nt 100% in Order.

??? Your Client uses a Timstamp too ???
You didn't do that without reason ;-)

al other formatstrings are examples from „great“ platforms.

I'm looking forward to the revised version.
Then I will start a long-term measurement of the transmission quality.

Ludwich

**Comment by webspiderteam** [comment]
> about timestamp: a timestamp is useful to find the right order, MQTT is caching messages if connection is lost or broken. i meen Transfer is’nt 100% in Order.

Ok I got it



> ??? Your Client uses a Timstamp too ??? You didn't do that without reason ;-)

No.. Its just test clients timer. and I know that you will want time :) thats why I put :)




> please change to JSON Format with Key:Value format.

will doo in an hour I think.

BTW Can you do me a favor? I think I have to create wiki for app. and you are beteer than me at this.

**Comment by ludwich66** [comment]
No Problem we made it hand in hand :-)

> Am 31.07.2022 um 19:43 schrieb webspiderteam ***@***.***>:
> 
> BTW Can you do me a favor? I think I have to create wiki for app. and you are beteer than me at this.

**Comment by webspiderteam** [comment]
[BluetoothDMM.zip](https://github.com/webspiderteam/Bluetooth_DMM_For_Windows_MQTT_Test_Project/files/9229475/BluetoothDMM.zip)
this should be enough :)

**Comment by ludwich66** [comment]
New Test:

Sorry for my false examples before!!

**JSON Parsing Error**
actual JSON string:
"{ Time:"31.07.2022 20:56:30",Device:"Bluetooth DMM" ,Value:"  25", Range:"°C", Current:""}"
 _we need more "quotes" and deleting blanks_ 

I mean this works better ;-)
`"{"Time":"31.07.2022 20:56:30","Device":"Bluetooth DMM","Value":"  25","Range":"°C","Current":""}"`

<img width="583" alt="image" src="https://user-images.githubusercontent.com/12202733/182041968-d7b39bdd-f01d-476a-a11f-cf5f81640880.png">

https://jsonformatter.curiousconcept.com/#

**Comment by webspiderteam** [comment]
Done :) I left blanks as is but absent keys worse than blanks I think.
[BluetoothDMM.zip](https://github.com/webspiderteam/Bluetooth_DMM_For_Windows_MQTT_Test_Project/files/9229575/BluetoothDMM.zip)

**Comment by ludwich66** [comment]
Please check the string in the validator, i dont see changes in the last exe.?
validator error is present at time

**Comment by webspiderteam** [comment]
![image](https://user-images.githubusercontent.com/85828505/182043060-22c99100-eb62-4967-b926-f8e176ad9620.png)
i did...
maybe the file was wrong

**Comment by webspiderteam** [comment]
[BluetoothDMM.zip](https://github.com/webspiderteam/Bluetooth_DMM_For_Windows_MQTT_Test_Project/files/9229639/BluetoothDMM.zip)
recompiled

**Comment by ludwich66** [comment]
did you send a updatefile?
id like to test this night ;-)

**Comment by webspiderteam** [comment]
sended just a minute ago

**Comment by ludwich66** [comment]
NodeRed View
now its a valid JSON Object

![image](https://user-images.githubusercontent.com/12202733/182043396-9b4c5dbb-b0ec-4e87-9ad1-24d7591be882.png)

I run this night a longperiode test with chart and filesaving on Nodered side
V05B --> BTDMM --> MosquittoBroker --> NodeRed-Client --> Filesave

CU tomorrow 
ludwich

**Comment by ludwich66** [comment]
But there is the little problem with
string "  25" and 
Int value 25.
 hope we can find another way here, you can't calculate with a string...

**Comment by webspiderteam** [comment]
it has to be float value but if we send it like that u cant get AUTO and NCV but you can easyly convert it if its string. just with 1 line code

**Comment by ludwich66** [comment]
Idea 
send
„Value“:1234   —> Float  1234  25.00  and
„Display“:“string“ —> Auto .OL „  25“ etc.

but more tomorrow (sleep a night over ideas first…)

**Comment by ludwich66** [comment]
please see https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/discussions/10

**Comment by ludwich66** [comment]
Info Date Time format changes with localization.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/12202733/182244361-d03f1cba-fec3-4213-a048-3c39da3b1ad2.png">
